# Generated by Django 2.1.3 on 2018-11-26 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='evi_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
