# Generated by Django 2.1.3 on 2018-11-27 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_evidence_evi_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='pictures/'),
        ),
        migrations.AddField(
            model_name='evidence',
            name='record',
            field=models.FileField(blank=True, null=True, upload_to='records/'),
        ),
        migrations.AddField(
            model_name='evidence',
            name='signiture',
            field=models.ImageField(blank=True, null=True, upload_to='signitures/'),
        ),
    ]
