# Generated by Django 2.1.3 on 2018-11-27 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20181127_0010'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evi_case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.AddField(
            model_name='evidence',
            name='evi_case',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Evi_case'),
        ),
    ]
